### ISSUE TITLE
file "training_prob_t1.csv" seems missing

### ISSUE THREAD

**Issue by RainyInMay** [tju-chenyaosuo/COTest#1]
![屏幕截图 2024-05-06 165719](https://github.com/tju-chenyaosuo/COTest/assets/69957642/38e8e5f3-83c0-4a9c-9c12-4d186e703fe2)

Hello, I'd like to try using COTest, but it seems that the file  `training_prob_t1.csv` mentioned in `LLVM-COTest.py` and `GCC-COTest.py` is missing. How can I obtain the `training_prob_t1.csv` file? And can you tell me more detail about how to run this project?

**Comment by tju-chenyaosuo** [comment]
Hello,
this file is automatically generated by Csmith modified in HiCOND[1], you can get the modified Csmith in this repository: [https://github.com/JunjieChen/HiCOND/tree/master/tool/csmith_recorder](url).
The modified Csmith records some features of generated test program, such as the number of program elements.

[1] Chen J, Wang G, Hao D, et al. History-guided configuration diversification for compiler test-program generation[C]//2019 34th IEEE/ACM International Conference on Automated Software Engineering (ASE). IEEE, 2019: 305-316.

**Comment by RainyInMay** [comment]
ok, thanks!
